version: '3.9'

services:
  # Interfaz Web de Configuraci贸n (Streamlit)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config_app_web
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app  # Sincronizaci贸n de c贸digo para desarrollo en vivo
      # El siguiente volumen monta los secretos de streamlit en el contenedor
      - ./.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro
    ports:
      - "8501:8501"
    networks:
      - config_app_net
    restart: unless-stopped
    depends_on:
      - ollama # Asegurarse de que Ollama se inicie primero

  # Servicio para el modelo Llama 3
  ollama:
    image: ollama/ollama
    container_name: ollama_service
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - config_app_net
    restart: unless-stopped

# Red para la comunicaci贸n
networks:
  config_app_net:
    driver: bridge

# Volumen para persistir los modelos de Ollama
volumes:
  ollama_data: {}
