version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: jdmmitagente_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=jdmmitagente_db
      - MYSQL_USER=jdmmit_user
      - MYSQL_PASSWORD=jdmmit_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: jdmmitagente_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  jdmmitagente:
    build: .
    container_name: jdmmitagente_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - .env:/app/.env:ro
    depends_on:
      mysql:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - DB_HOST=mysql
      - DB_TYPE=mysql
    command: python jdmmitagente.py
    restart: unless-stopped

volumes:
  mysql_data:
  ollama_data:
